/**
 * Various options that can be passed to an model class.
 */
export type ModelOptions = {
  /**
   * Namespace where instances of the model will be stored into. If omitted,
   * one will be generated by slugifying the class name.
   */
  namespace?: string;
};
